#!/usr/bin/env bash
# Configure domain zone

if [ "$#" -eq  0 ]; then
	exit 1
fi

# Display subdomain info
display_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type
    local destination

    record_type=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:/ {getline; print $4}')
    destination=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:/{getline; print $NF}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Display default subdomain info
display_default_subdomains_info() {
    local domain="$1"
    display_subdomain_info "$domain" www
    display_subdomain_info "$domain" lb-01
    display_subdomain_info "$domain" web-01
    display_subdomain_info "$domain" web-02
}

main() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        display_default_subdomains_info "$domain"
    else
        display_subdomain_info "$domain" "$subdomain"
    fi
}

# Call main
main "$1" "$2"
