#!/usr/bin/env bash
# transfers a file from our client to a server
if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

FILE_PATH=$1
IP_ADDR=$2
USERNAME=$3
IDENTITY_FILE=$4

scp -i "$IDENTITY_FILE" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$IP_ADDR:~/"
