#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install nginx -y

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "server {
	listen 80 default_server;
	root /etc/nginx/html
	location / {
		index index.htm index.html;
	}
}" > "/etc/nginx/sites-available/default"

echo "Hello World!" > /etc/nginx/html/index.html

sudo service nginx restart
