#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install nginx -y

echo "server {
	listen 80 default_server;
	root /var/www/html
	location / {
		index index.htm index.html;
	}
}" > "/etc/nginx/sites-available/default"

echo "Hello World!" > /var/www/html/index.html



sudo service nginx restart
