#!/usr/bin/env bash
# Set up nginx which adds custom header
apt-get -y update
apt-get -y install nginx
echo "server {
    listen 80 default_server;
    root /var/www/html;
    error_page 404 /not_found.html;
    add_header X-Served-By $HOSTNAME;
    location /redirect_me {
        return 301 https://www.bing.com;
    }
    location / {
        index index.htm index.html;
    }
}" > "/etc/nginx/sites-available/default"
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/not_found.html
service nginx start
