#!/usr/bin/env bash
# Set up nginx which adds custom header
apt-get install nginx -y
echo "server {
	listen 80 default_server;
	add_header X-Served-By $HOSTNAME;
}" > "/etc/nginx/sites-enabled/default"

sudo service nginx restart
