#!/usr/bin/env bash
# Install load balancer on lb-01 server
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get update
sudo apt-get install haproxy=2.8.\*

echo "
frontend listener
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 203035-web-01 52.206.61.240:80 check
        server 203035-web-02 54.144.158.52:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
