#!/usr/bin/env bash
# Install load balancer on lb-01 server
apt-get update
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.8 -y
apt-get update -y
apt-get install haproxy=2.8.\* -y

echo "
frontend listener
        bind *:80
		mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server 203035-web-01 52.206.61.240:80 check
        server 203035-web-02 54.144.158.52:80 check" >> /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
