#!/usr/bin/env bash
# Install load balancer on lb-01 server
apt-get update -y
apt-get install haproxy -y

echo "
frontend listener
	bind *:80
	mode http
	default_backend web-backend

backend web-backend
	balance roundrobin
	mode http
	server 203035-web-01 52.206.61.240:80 check
	server 203035-web-02 54.144.158.52:80 check
" >> /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
