#!/usr/bin/env bash
# debug curl error: 'Failed to connect to 0 port 80: Connection refused'
rm -rf /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
