#!/usr/bin/env bash
# display the visitor IP along with the HTTP status code from Apacge log file
awk '{print $1, $9}' apache-access.log | awk '{ count[$0]++ } END { for (line in count) printf "%d %s\n", count[line], line }' | sort -nr
