#!/usr/bin/env bash
# displays "Best School" 10 times and prints hi on the 9th iteration
counter=1
while [ "$counter" -le 10 ]
do 
	echo "Best School"
	if [ "$counter" = "9" ]; then
		printf "Hi\n"
	fi
	counter=$(( counter + 1 ))
done
