#!/usr/bin/env bash
# display numbers from 1 - 20
# do special echos on numbers 4, 9 and 17
i=1
while [ "$i" -le 20 ]
do
	case $i in
		"4")
			printf "%d\nbad luck from China\n" "$i"
			;;
		"9")
			printf "%d\nbad luck from Japan\n" "$i"
			;;
		"17")
			printf "%d\nbad luck from Italy\n" "$i"
			;;
		*)
			echo "$i"
	esac
	i=$(( i + 1 ))
done
