#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
hour=0
while [ "$hour" -le 12 ]
do
	printf "Hour: %d\n" "$hour"
	(( hour++ ))
	minute=1
	while [ "$minute" -le 59 ]
		do
			echo "$minute"
			(( minute++ ))
		done
done
